# Generated by Django 3.1.7 on 2021-06-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Blog Title')),
                ('description', models.TextField(verbose_name='Blog Description')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Upload Picture')),
                ('featured', models.BooleanField(default=False, verbose_name='Is Featured')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
